In [149]:
import pandas as pd
import numpy as np
import pprint as pprint
import matplotlib.pyplot as plt
import re
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

VADER (Valence Aware Dictionary and sEntiment Reasoner) is a lexicon and rule-based sentiment analysis tool that is specifically attuned to sentiments expressed in social media.

VADER: A Parsimonious Rule-based Model for Sentiment Analysis of Social Media Text
(by C.J. Hutto and Eric Gilbert)
Eighth International Conference on Weblogs and Social Media (ICWSM-14). Ann Arbor, MI, June 2014.

https://github.com/cjhutto/vaderSentiment

In [123]:
news_data = pd.read_csv('news_events.csv',encoding="ISO-8859-1",parse_dates={'Date':[0,1,2]})
news_data.index = pd.to_datetime(news_data['Date'])
news_data = news_data.drop('Date',axis=1)
news_data.head()

,description,title
Date,,
2018-03-23 13:00:00,The cryptocurrency markets regained some poise...,ICON to EOS: 3 Cryptos Are Leading the Market ...
2018-03-23 11:00:00,Yahoo Japan is planning to launch its own cryp...,Yahoo Japan to Launch Cryptocurrency Exchange ...
2018-03-23 10:00:00,Bitcoin's retreat from the 200-day moving aver...,$8K? Bitcoin Under Pressure After Rejection at...
2018-03-22 14:00:00,EOS has jumped 70 percent in the last few days...,EOS Eyes Bull Reversal After 70 Percent Spike
2018-03-22 12:00:00,BloXroute's founder worries relay networks tha...,Better Bitcoin Relay? Crypto VCs Back BloXrout...

In [124]:
index = pd.date_range(start='1/1/2017', end='23/03/2018',freq='1H',normalize=True)

The compound score is computed by summing the valence scores of each word in the lexicon, adjusted according to the rules, and then normalized to be between -1 (most extreme negative) and +1 (most extreme positive). This is the most useful metric if you want a single unidimensional measure of sentiment for a given sentence. Calling it a 'normalized, weighted composite score' is accurate.

It is also useful for researchers who would like to set standardized thresholds for classifying sentences as either positive, neutral, or negative. Typical threshold values (used in the literature cited on this page) are:

positive sentiment: compound score >= 0.05
neutral sentiment: (compound score > -0.05) and (compound score < 0.05)
negative sentiment: compound score <= -0.05

In [125]:
analyzer = SentimentIntensityAnalyzer()
news_data['sentiment'] = news_data['title'].apply(lambda x:analyzer.polarity_scores(x)['compound'])

In [126]:
news_data.head()

,description,title,sentiment
Date,,,
2018-03-23 13:00:00,The cryptocurrency markets regained some poise...,ICON to EOS: 3 Cryptos Are Leading the Market ...,0.0000
2018-03-23 11:00:00,Yahoo Japan is planning to launch its own cryp...,Yahoo Japan to Launch Cryptocurrency Exchange ...,0.0000
2018-03-23 10:00:00,Bitcoin's retreat from the 200-day moving aver...,$8K? Bitcoin Under Pressure After Rejection at...,-0.6908
2018-03-22 14:00:00,EOS has jumped 70 percent in the last few days...,EOS Eyes Bull Reversal After 70 Percent Spike,0.0000
2018-03-22 12:00:00,BloXroute's founder worries relay networks tha...,Better Bitcoin Relay? Crypto VCs Back BloXrout...,0.4404

In [127]:
news_data = news_data[~news_data.index.duplicated()]
news_data = news_data.reindex(index)

In [129]:
news_data = news_data.fillna(value={'sentiment':0})

In [137]:
news_data = news_data.drop('description',axis=1)

In [145]:
news_data['event'] = 1
news_data['event'][news_data['title'].isnull()] = 0

C:\Users\farazz\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [147]:
news_data.to_csv('news_data_sentiment.csv')

In [148]:
news_data

,title,sentiment,event
2017-01-01 00:00:00,NaN,0.0000,0
2017-01-01 01:00:00,NaN,0.0000,0
2017-01-01 02:00:00,NaN,0.0000,0
2017-01-01 03:00:00,NaN,0.0000,0
2017-01-01 04:00:00,NaN,0.0000,0
2017-01-01 05:00:00,NaN,0.0000,0
2017-01-01 06:00:00,NaN,0.0000,0
2017-01-01 07:00:00,NaN,0.0000,0
2017-01-01 08:00:00,NaN,0.0000,0
2017-01-01 09:00:00,NaN,0.0000,0
2017-01-01 10:00:00,NaN,0.0000,0
2017-01-01 11:00:00,NaN,0.0000,0
2017-01-01 12:00:00,NaN,0.0000,0
2017-01-01 13:00:00,NaN,0.0000,0
2017-01-01 14:00:00,NaN,0.0000,0
2017-01-01 15:00:00,NaN,0.0000,0
2017-01-01 16:00:00,NaN,0.0000,0
2017-01-01 17:00:00,NaN,0.0000,0
2017-01-01 18:00:00,NaN,0.0000,0
2017-01-01 19:00:00,NaN,0.0000,0
2017-01-01 20:00:00,NaN,0.0000,0
2017-01-01 21:00:00,"Bitcoin Price Tops $1,000 in First Day of 2017...",0.5106,1
2017-01-01 22:00:00,NaN,0.0000,0
2017-01-01 23:00:00,NaN,0.0000,0
2017-01-02 00:00:00,NaN,0.0000,0
2017-01-02 01:00:00,NaN,0.0000,0
2017-01-02 02:00:00,NaN,0.0000,0
2017-01-02 03:00:00,NaN,0.0000,0
2017-01-02 04:00:00,NaN,0.0000,0
2017-01-02 05:00:00,NaN,0.0000,0
...,...,...,...
2018-03-21 19:00:00,NaN,0.0000,0
2018-03-21 20:00:00,NaN,0.0000,0
2018-03-21 21:00:00,NaN,0.0000,0
2018-03-21 22:00:00,NaN,0.0000,0
2018-03-21 23:00:00,NaN,0.0000,0
2018-03-22 00:00:00,NaN,0.0000,0
2018-03-22 01:00:00,NaN,0.0000,0
2018-03-22 02:00:00,NaN,0.0000,0
2018-03-22 03:00:00,NaN,0.0000,0
2018-03-22 04:00:00,NaN,0.0000,0
2018-03-22 05:00:00,NaN,0.0000,0
2018-03-22 06:00:00,NaN,0.0000,0
2018-03-22 07:00:00,NaN,0.0000,0
2018-03-22 08:00:00,NaN,0.0000,0
2018-03-22 09:00:00,NaN,0.0000,0
2018-03-22 10:00:00,Pullback Ahead? Bitcoin Hits Stiff Resistance ...,0.0000,1
2018-03-22 11:00:00,Korean Regulators to Probe Bank AML Measures f...,0.7297,1
2018-03-22 12:00:00,Better Bitcoin Relay? Crypto VCs Back BloXrout...,0.4404,1
2018-03-22 13:00:00,NaN,0.0000,0
2018-03-22 14:00:00,EOS Eyes Bull Reversal After 70 Percent Spike,0.0000,1
2018-03-22 15:00:00,NaN,0.0000,0
2018-03-22 16:00:00,NaN,0.0000,0
2018-03-22 17:00:00,NaN,0.0000,0
2018-03-22 18:00:00,NaN,0.0000,0
2018-03-22 19:00:00,NaN,0.0000,0
2018-03-22 20:00:00,NaN,0.0000,0
2018-03-22 21:00:00,NaN,0.0000,0
2018-03-22 22:00:00,NaN,0.0000,0
2018-03-22 23:00:00,NaN,0.0000,0
2018-03-23 00:00:00,NaN,0.0000,0